Syndicata/Models/Copropriete.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.ComponentModel;


namespace Syndicata.Models
{
    public class Copropriete
    {
        public int Id { get; set; }

        [DisplayName("Nom de copropriété : ")]
        [Required]
        public string Nom { get; set; }

        [DisplayName("Trésorerie de copropriété : ")]
        public decimal Tresorerie { get; set; }

        [Required]
        [Range(1900, 9999)]
        [DisplayName("L'année de construction : ")]
        public int AnneConstruction { get; set; }


        [DisplayName("Syndic de copropriété : ")]
        public Person Syndic { get; set; }
        public int SyndicId { get; set; }

        [DisplayName("Adjoint de copropriété : ")]
        public Person SyndicAdjoint { get; set; }
        public int SyndicAdjointId { get; set; }

        public ICollection<Appartement> Appartements { get; set; }
        public ICollection<AssembleGeneral> AssembleGenerals { get; set; }
        public ICollection<Commande> Commandes { get; set; }
    }
}

Syndicata/Controllers/AppartementsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Syndicata.Data;
using Syndicata.Models;

namespace Syndicata.Controllers
{
    public class AppartementsController : Controller
    {
        private SyndicataContext db = new SyndicataContext();

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            string actionName = filterContext.ActionDescriptor.ActionName;
            string controllerName = filterContext.ActionDescriptor.ControllerDescriptor.ControllerName;
            Person user = Session["userInfo"] as Person;
            if (user == null || !Helper.CheckAutorization(actionName, controllerName, user.RoleId))
            {
                filterContext.Result = new RedirectToRouteResult(
                    new RouteValueDictionary
                    {
                        {"controller", "Home"},
                        {"action", "NoAccess"}
                    });
                return;
            }
        }

        // GET: Appartements
        public ActionResult Index()
        {
            var appartements = db.Appartements.Include(a => a.Propritaire).Include(a => a.Residence);
            return View(appartements.ToList());
        }

        // GET: Appartements/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appartement appartement = db.Appartements.Include(_ => _.Propritaire).Include(_ => _.Residence).SingleOrDefault(_ => _.Id == id);
            if (appartement == null)
            {
                return HttpNotFound();
            }
            return View(appartement);
        }

        // GET: Appartements/Create
        public ActionResult Create()
        {
            ViewBag.PropritaireId = new SelectList(db.People.Where(_ => _.RoleId == Role.Copropritaire), "Id", "FullName");
            ViewBag.ResidenceId = new SelectList(db.Coproprietes, "Id", "Nom");
            return View();
        }

        // POST: Appartements/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,NumeroAppartement,Surface,Etage,ResidenceId,PropritaireId")] Appartement appartement)
        {
            if (ModelState.IsValid)
            {
                db.Appartements.Add(appartement);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PropritaireId = new SelectList(db.People.Where(_ => _.RoleId == Role.Copropritaire), "Id", "FullName");
            ViewBag.ResidenceId = new SelectList(db.Coproprietes, "Id", "Nom", appartement.ResidenceId);
            return View(appartement);
        }

        // GET: Appartements/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appartement appartement = db.Appartements.Find(id);
            if (appartement == null)
            {
                return HttpNotFound();
            }
            ViewBag.PropritaireId = new SelectList(db.People.Where(_ => _.RoleId == Role.Copropritaire), "Id", "FullName");
            ViewBag.ResidenceId = new SelectList(db.Coproprietes, "Id", "Nom", appartement.ResidenceId);
            return View(appartement);
        }

        // POST: Appartements/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,NumeroAppartement,Surface,Etage,ResidenceId,PropritaireId")] Appartement appartement)
        {
            if (ModelState.IsValid)
            {
                db.Entry(appartement).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PropritaireId = new SelectList(db.People.Where(_ => _.RoleId == Role.Copropritaire), "Id", "FullName");
            ViewBag.ResidenceId = new SelectList(db.Coproprietes, "Id", "Nom", appartement.ResidenceId);
            return View(appartement);
        }

        // GET: Appartements/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appartement appartement = db.Appartements.Find(id);
            if (appartement == null)
            {
                return HttpNotFound();
            }
            return View(appartement);
        }

        // POST: Appartements/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Appartement appartement = db.Appartements.Find(id);
            db.Appartements.Remove(appartement);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Syndicata/Controllers/CommandesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Syndicata.Data;
using Syndicata.Models;

namespace Syndicata.Controllers
{
    public class CommandesController : Controller
    {
        private SyndicataContext db = new SyndicataContext();

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            string actionName = filterContext.ActionDescriptor.ActionName;
            string controllerName = filterContext.ActionDescriptor.ControllerDescriptor.ControllerName;
            Person user = Session["userInfo"] as Person;
            if (user == null || !Helper.CheckAutorization(actionName, controllerName, user.RoleId))
            {
                filterContext.Result = new RedirectToRouteResult(
                    new RouteValueDictionary
                    {
                        {"controller", "Home"},
                        {"action", "NoAccess"}
                    });
                return;
            }
        }

        // GET: Commandes
        public ActionResult Index()
        {
            var commandes = db.Commandes.Include(c => c.Copropriete).Include(c => c.Syndic);
            return View(commandes.ToList());
        }

        // GET: Commandes/Details/5
        public ActionResult Details(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Commande commande = db.Commandes.Find(id);
            if (commande == null)
            {
                return HttpNotFound();
            }
            return View(commande);
        }

        // GET: Commandes/Create
        public ActionResult Create()
        {
            Person user = Session["userInfo"] as Person;
            ViewBag.CoproprieteId = 
                new SelectList(db.Coproprietes.Where(_ => _.SyndicId == user.Id || _.SyndicAdjointId == user.Id), "Id", "Nom");
            return View();
        }

        // POST: Commandes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Montant,Description,CoproprieteId")] Commande commande)
        {
            Person user = Session["userInfo"] as Person;

            if (ModelState.IsValid)
            {
                commande.DateCommande = DateTime.Now;
                commande.SyndicId = user.Id;
                db.Commandes.Add(commande);
                db.SaveChanges();
                var copropriete = db.Coproprietes.SingleOrDefault(_ => _.Id == commande.CoproprieteId);
                if(copropriete != null)
                {
                    copropriete.Tresorerie -= commande.Montant;
                    db.Entry(copropriete).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            ViewBag.CoproprieteId =
                new SelectList(db.Coproprietes.Where(_ => _.SyndicId == user.Id || _.SyndicAdjointId == user.Id), "Id", "Nom");
            ViewBag.SyndicId = user.Id;
            return View(commande);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Syndicata/Controllers/CoproprietesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Syndicata.Data;
using Syndicata.Models;

namespace Syndicata.Controllers
{
    public class CoproprietesController : Controller
    {
        private SyndicataContext db = new SyndicataContext();

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            string actionName = filterContext.ActionDescriptor.ActionName;
            string controllerName = filterContext.ActionDescriptor.ControllerDescriptor.ControllerName;
            Person user = Session["userInfo"] as Person;
            if (user == null || !Helper.CheckAutorization(actionName, controllerName, user.RoleId))
            {
                filterContext.Result = new RedirectToRouteResult(
                    new RouteValueDictionary
                    {
                        {"controller", "Home"},
                        {"action", "NoAccess"}
                    });
                return;
            }
        }

        // GET: Coproprietes
        public ActionResult Index()
        {
            var coproprietes = db.Coproprietes.Include(c => c.Syndic).Include(c => c.SyndicAdjoint);
            return View(coproprietes.ToList());
        }

        // GET: Coproprietes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Copropriete copropriete = db.Coproprietes
                .Include(_ => _.Syndic)
                .Include(_ => _.SyndicAdjoint)
                .Include(_ => _.Appartements)
                .Include(_ => _.AssembleGenerals)
                .Include(_ => _.Commandes)
                .SingleOrDefault(_ => _.Id == id);
            if (copropriete == null)
            {
                return HttpNotFound();
            }
            return View(copropriete);
        }

        // GET: Coproprietes/Create
        public ActionResult Create()
        {
            var syndics = db.People.Where(_ => _.RoleId == Role.Syndic);
            ViewBag.SyndicId = new SelectList(syndics, "Id", "FullName");
            ViewBag.SyndicAdjointId = new SelectList(syndics, "Id", "FullName");
            return View();
        }

        // POST: Coproprietes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nom,Tresorerie,AnneConstruction,SyndicId,SyndicAdjointId")] Copropriete copropriete)
        {
            if (ModelState.IsValid)
            {
                db.Coproprietes.Add(copropriete);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            var syndics = db.People.Where(_ => _.RoleId == Role.Syndic);
            ViewBag.SyndicId = new SelectList(syndics, "Id", "FullName");
            ViewBag.SyndicAdjointId = new SelectList(syndics, "Id", "FullName");
            return View(copropriete);
        }

        // GET: Coproprietes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Copropriete copropriete = db.Coproprietes.Find(id);
            if (copropriete == null)
            {
                return HttpNotFound();
            }
            var syndics = db.People.Where(_ => _.RoleId == Role.Syndic);
            ViewBag.SyndicId = new SelectList(syndics, "Id", "FullName");
            ViewBag.SyndicAdjointId = new SelectList(syndics, "Id", "FullName"); 
            return View(copropriete);
        }

        // POST: Coproprietes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nom,Tresorerie,AnneConstruction,SyndicId,SyndicAdjointId")] Copropriete copropriete)
        {
            if (ModelState.IsValid)
            {
                db.Entry(copropriete).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            var syndics = db.People.Where(_ => _.RoleId == Role.Syndic);
            ViewBag.SyndicId = new SelectList(syndics, "Id", "FullName");
            ViewBag.SyndicAdjointId = new SelectList(syndics, "Id", "FullName");
            return View(copropriete);
        }

        // GET: Coproprietes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Copropriete copropriete = db.Coproprietes.Find(id);
            if (copropriete == null)
            {
                return HttpNotFound();
            }
            return View(copropriete);
        }

        // POST: Coproprietes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Copropriete copropriete = db.Coproprietes.Find(id);
            db.Coproprietes.Remove(copropriete);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Syndicata/Views/Coproprietes/Create.cshtml
@model Syndicata.Models.Copropriete

@{
    ViewBag.Title = "Creer une copropriété";
}

<div class="container margin-bottom-15">
    <h2 class="margin-bottom-1-em">Créer une nouvelle copropriété</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Tresorerie, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Tresorerie, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Tresorerie, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AnneConstruction, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AnneConstruction, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AnneConstruction, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SyndicId, "SyndicId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("SyndicId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SyndicId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SyndicAdjointId, "SyndicAdjointId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("SyndicAdjointId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SyndicAdjointId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Creer" class="btn btn-default btn-block" />
                </div>
            </div>
        </div>
    }

    <div>
        <p>
            @Html.ActionLink("Retourner a la liste des copropriétés", "Index", null, new { @class = "btn btn-danger float-right margin-right-0-5-em" })
        </p>
    </div>

</div>

Syndicata/Views/Coproprietes/Delete.cshtml
@model Syndicata.Models.Copropriete

@{
    ViewBag.Title = "Delete";
 
}

<div class="container margin-bottom-15">
    <h2 class="margin-bottom-1-em">Supprimer la copropriété</h2>
    <h3 class="margin-bottom-1-em">Êtes-vous sûr de vouloir le supprimer?</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Syndic.Nom)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Syndic.Nom)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SyndicAdjoint.Nom)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SyndicAdjoint.Nom)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Nom)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nom)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Tresorerie)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Tresorerie)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AnneConstruction)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AnneConstruction)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <div>
            <p>
                @Html.ActionLink("Retourner a la liste des copropriétés", "Index", null, new { @class = "btn btn-danger float-right margin-right-0-5-em" })
            </p>
        </div>

    </div> 
        }
    </div>
</div>

Syndicata/Views/Coproprietes/Details.cshtml
@model Syndicata.Models.Copropriete

@{
    ViewBag.Title = "Details";
 
}

<div class="container margin-bottom-15">
    <h2 class="margin-bottom-1-em">Details de la copropriété : @Model.Nom</h2>

    <div>
        <h4>Copropriete</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nom)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nom)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Tresorerie)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Tresorerie)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AnneConstruction)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AnneConstruction)
            </dd>


            <dt>
                Nombre d'appartements habitable:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Appartements.Count)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Syndic)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Syndic.FullName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SyndicAdjoint)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SyndicAdjoint.FullName)
            </dd>

        </dl>
    </div>

    <br />
    <div>
        <h4>Liste des appartements de la copropriete : @Model.Nom </h4>
        <table class="table">
            <tr>
                <th>
                    Numero de l'appartement :
                </th>
                <th>
                    Surface :
                </th>
                <th>
                    Etage :
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.Appartements)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.NumeroAppartement)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Surface)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Etage)
                    </td>
                    <td>
                        @Html.ActionLink("Voir plus de details", "Details", "Appartements", new { id = item.Id }, null)
                    </td>
                </tr>
            }
        </table>

        <br />
        <h4>Liste des assembles generale de la copropriete : @Model.Nom </h4>
        <table class="table">
            <tr>

                <th>
                    Assemble generale n°
                </th>

                <th>
                    Motif
                </th>

                <th>
                    Date de l'assemble generale
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.AssembleGenerals)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Motif)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateAssemble)
                    </td>
                    <td>
                        @Html.ActionLink("voir plus de Details", "Details", new { id = item.Id }, null)
                    </td>
                </tr>
            }
        </table>

        <br />
        <div>
            <h4>Liste des commandes passés pour la copropriete @Model.Nom </h4>
            <table class="table">
                <tr>
                    <th>
                        Description :
                    </th>
                    <th>
                        Montant :
                    </th>
                    <th>
                        Date de la commande :
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model.Commandes)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Montant)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DateCommande)
                        </td>
                        <td>
                            @Html.ActionLink("Voir plus de details", "Details", "Commandes", new { id = item.Id }, null)
                        </td>
                    </tr>
                }
            </table>
        </div>

        <div>
            <p>
                @Html.ActionLink("Modifier le copropriété", "Edit", new { id = Model.Id }, new { @class = "btn btn-danger float-right" })
                @Html.ActionLink("Retourner a la liste des copropriétés", "Index", null, new { @class = "btn btn-danger float-right margin-right-0-5-em" })
            </p>
        </div>

    </div>

Syndicata/Views/Coproprietes/Edit.cshtml
@model Syndicata.Models.Copropriete

@{
    ViewBag.Title = "Modification de copropriété";
 
}

<div class="container margin-bottom-15">
    <h2 class="margin-bottom-1-em">Modifier la copropriété</h2>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Tresorerie, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Tresorerie, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Tresorerie, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AnneConstruction, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AnneConstruction, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AnneConstruction, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SyndicId, "SyndicId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("SyndicId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SyndicId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SyndicAdjointId, "SyndicAdjointId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("SyndicAdjointId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SyndicAdjointId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Enregistrer" class="btn btn-default btn-block" />
                </div>
            </div>
        </div>
    }

    <div>
        <p>
            @Html.ActionLink("Retourner a la liste des copropriétés", "Index", null, new { @class = "btn btn-danger float-right margin-right-0-5-em" })
        </p>
    </div>

</div>